# Numpy

Numpy menyediakan fungsi yang siap pakai untuk memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.

List dan math memang bisa kita pakai buat perhitungan saintifik. Namun masih kurang lengkap, karena beberapa operasi perhitungan harus kita buat secara manual.

In [ ]:
import numpy as np

## Membuat Array

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('elemen ke dua dari row 1\n', arr[0, 1])

elemen ke dua dari row 1
 2


### Membuat dan mengisi array secara otomatis

In [ ]:
# Array berisi angka 1 (satu)
ones = np.ones((3, 2)) # Membuat matriks 3x2 berisi 1
print(f"\nArray satu ukuran 3x2: \n{ones}")

# np.arange(start, stop, step)
rentang = np.arange(0, 10, 2) # Angka 0 sampai 9, lompat 2
print(f"\nArray Arange: \n{rentang}")


Array satu ukuran 3x2: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Array Arange: 
[0 2 4 6 8]


Dengan numpy kita bisa melakukan operasi pada matriks dengan mudah

## Operasi Matrik

Dengan Numpy kita bisa melakukan operasi tambah,kurang,bagi dan juga kali dengan sangat gampang

In [ ]:
matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])

hasil = matrik_a + matrik_b
print(hasil)

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


Jika tidak menggunakan Numpy kita harus melakukan dengan looping secara manual

In [ ]:
#tanpa numpy
matrik_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

matrik_b = [
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]]

hasil = []
for i in range(len(matrik_a)):
    baris_hasil = []
    for j in range(len(matrik_a[0])):
        jumlah_elemen = matrik_a[i][j] + matrik_b[i][j]
        baris_hasil.append(jumlah_elemen)
    hasil.append(baris_hasil)

print(hasil)

[[4, 4, 4], [10, 10, 10], [16, 16, 16]]


## Indexing

Cara akses index pada array di numpy sama seperti index array di python yaitu dengan cara nama_variabel[index]

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


## Slicing

Begitu juga untuk slicing sama seperti slicing list yang telah kalian pelajari sebelumnya

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) # start di index 3 dari belakang, dan end di index 1 dari belakang

[5 6]


atau kita juga bisa menerapkan step yaitu dengan cara nama_variabel[start:step:stop]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


# CRUD dengan Pandas

Apa itu Pandas? Pandas adalah library (pustaka) di Python yang khusus digunakan untuk analisis dan manipulasi data. Jika Anda pernah menggunakan Excel, Pandas adalah versi coding-nya yang jauh lebih canggih.

Apa itu DataFrame? Struktur data utama di Pandas adalah DataFrame. Anggap saja DataFrame ini sebagai tabel, sama seperti spreadsheet di Excel, yang memiliki baris dan kolom.


Import pandas dan numpy lalu gunakan 'as' untuk deklarasi aliasnya jadi memanggil fungsinya menggunakan 'as' nya terlebih dahulu

In [ ]:
import pandas as pd
import numpy as np

## Membuat file CSV dengan python

In [ ]:
# data awal string
data_awal = """NIM,Nama,Angkatan
23001,Budi Santoso,2023
23002,Ani Wijaya,2023
23003,Citra Lestari,2023
23004,Doni Firmansyah,2023
"""

try:
    with open("mahasiswa.csv", "w") as f:
        f.write(data_awal) #khusus string
    print("File 'mahasiswa.csv' berhasil dibuat!")
except Exception as e:
    print(f"Gagal membuat file: {e}")

Membuat file CSV dengan dataframe

In [ ]:
dataAwal = {
    'NIM': [2409106046],
    'Nama': ['st'],
    'Angkatan': ['2024']
}

try:
    df = pd.DataFrame(dataAwal) #ubah dictionary menjadi dataframe
    
    df.to_csv("mahasiswa2.csv", index=False)# index=False penting agar nomor index (0) tidak ikut disimpan
    print("File 'mahasiswa2.csv' berhasil dibuat dengan data!")

except Exception as e:
    print(f"Gagal membuat file: {e}")

## Membaca dan Menampilkan Data

In [ ]:
# Untuk membaca file csv dan menyimpannya ke dataframe (df)
df = pd.read_csv("mahasiswa.csv")

In [ ]:
print(df)

Menampilkan 5 Baris Pertama Ini adalah cara yang paling umum digunakan untuk memeriksa apakah data sudah terbaca dengan benar. Gunakan .head(), begitu juga untuk tail

In [ ]:
print(df.head()) #menampilkan 5 teratas, jika menulis df.head(3) berarti menampilkan 3 teratas
print(df.tail()) #menampilkan 5 terbawah, jika menulis df.tail(3) berarti menampilkan 3 terbawah

kita bisa gunakan df.info() untuk melihat informasi ringkas dari dataframe yang kita miliki

In [ ]:
print(df.info()) #buat ngeliat informasi ringkas

## Update Data

Kita bisa gunakan .loc[index, namaKolom] = 'data Baru' untuk mengubah data menggunakan index

In [ ]:
# Data Sebelum di update
print("Data Sebelum di Update")
print(df.head())

# mengubah pada index 1 di kolom "nama"
df.loc[1, 'Nama'] = 'Maria'

# Tampilkan data setelah diubah
print("\nData Setelah di Update")
print(df.head())

Jika kita ingin mengubah tanpa menggunakan index kita bisa mengakalinya dengan cara membuat variabel baru untuk menampung index yang ingin kita cari, jadi kita bisa gunakan [df['nama kolom'] == "nilai yang ingin dicari"].index

lalu gunakan df.loc tadi untuk mengubahnya

In [ ]:
carIndex = df[df['Nama'] == "Citra Lestari"].index
df.loc[carIndex, 'Angkatan']  = 2019
print(df)

## Tambah Data

Ada dua jenis penambahan data: menambah baris baru (mahasiswa baru) atau menambah kolom baru (info baru)

### Menambah Baris Baru

Untuk menambah baris adalah dengan membuat DataFrame kecil baru, lalu menggabungkannya (concat) dengan DataFrame lama

In [ ]:
dataDF = pd.read_csv('mahasiswa.csv')

nim = int(input('NIM yang ingin di input'))
nama = input('Nama yang ingin di input')
angkatan = int(input('Angkatan yang ingin di input'))

dataBaru = pd.DataFrame({'NIM': [nim], 'Nama': [nama], 'Angkatan': [angkatan]})
dataDF = pd.concat([dataDF, dataBaru], ignore_index=True)
print(dataDF)
dataDF.to_csv('mahasiswa.csv', index=False)

In [ ]:

dataBaru = {
'NIM': [23005],
'Nama': ['budi Putra'],
'Angkatan': [2023]
}

# ubah dictionary ke dataframe
df_baru = pd.DataFrame(dataBaru)

# 3.gabung dataframe lama dengan dataframe baru
df = pd.concat([df, df_baru], ignore_index=True)

print("\nData setelah ditambah Eka Putra:")
print(df)
df.to_csv('mahasiswa.csv', index=False)


### Menambah Kolom Baru

In [ ]:
#Buat nama kolom baru dan beri nilainya
df['Asal'] = 'Samarinda'

print("Data setelah ditambah kolom 'Asal':")
print(df)

## Hapus Data

In [ ]:
# Menghapus baris berdasarkan index-nya
# inplace=True berarti kita memodifikasi df secara langsung
print(df)
df.drop(index=1, inplace=True) #cara 1
df = df.drop(index=1) #cara 2

print("\nData setelah menghapus Citra (index 2):")
print(df)

In [ ]:
# Menghapus kolom 'Asal'
# axis=1 memberitahu pandas bahwa kita mau menghapus KOLOM
print(df)
df.drop('Asal', axis=1, inplace=True)

print("\nData setelah menghapus kolom 'Asal':")
print(df)

Metode ini tidak menghapus. Tetapi, kalian membuat DataFrame baru yang hanya berisi baris yang ingin kalian simpan
Logikanya dibalik: "Simpan semua baris yang TIDAK sama dengan nama yang ingin saya hapus."

In [ ]:
kondisi = df['Nama'] != 'Ekas Putra'
dfBaru = df[kondisi]
print(dfBaru)

In [ ]:
df_baru = df.reset_index(drop=True) #jika false dia membuat index baru
print(df_baru)

## Penerapan Iterows

Metode .iterrows() digunakan untuk melakukan looping (iterasi) pada setiap baris di DataFrame. Ini berguna ketika Kalian perlu melakukan operasi yang kompleks untuk setiap baris, yang sulit dilakukan dengan operasi standar Pandas.

In [ ]:
data = {'NIM': [19001, 23001], 'Nama': ['Citra', 'Budi'], 'Angkatan': [2019, 2023]}
df_benar = pd.DataFrame(data)
print("--- Data Awal ---")
print(df_benar)

for index, row in df_benar.iterrows():
    if row['Angkatan'] < 2020:
        # Gunakan .loc[index, 'NamaKolomBaru'] untuk mengubah DataFrame ASLI
        df_benar.loc[index, 'Status'] = 'Alumni'
    else:
        df_benar.loc[index, 'Status'] = 'Mahasiswa Aktif'

print("\n--- Hasil yang Benar (Data Berubah) ---")
print(df_benar)

--- Data Awal ---
     NIM   Nama  Angkatan
0  19001  Citra      2019
1  23001   Budi      2023

--- Hasil yang Benar (Data Berubah) ---
     NIM   Nama  Angkatan           Status
0  19001  Citra      2019           Alumni
1  23001   Budi      2023  Mahasiswa Aktif


# Basic Data Cleaning Pandas

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/orkvacy/dummy-data/refs/heads/main/dummyData.csv'
df = pd.read_csv(url)

print(df.head(5))

   entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
0          1     55000.0       9500.0                   2.0   
1          2     99500.0      12000.0                   4.0   
2          3     94500.0      15000.0                   6.0   
3          4     86500.0      12000.0                   1.0   
4          5     70500.0       8000.0                   4.0   

   biaya_rent_tempat_tinggal  total_pendapatan_tahunan tingkat_pendidikan  \
0                       2375                  580500.0       Diploma (D3)   
1                       7153                 1116000.0        Master (S2)   
2                      11752                 1024000.0        Doktor (S3)   
3                          0                 1058500.0        Doktor (S3)   
4                          0                 1003000.0        Master (S2)   

   jumlah_pekerja_di_keluarga         kota  
0                         1.0  Bekasi Kota  
1                         1.0    Tangerang  
2                      

## Cek Nilai yang Hilang (Missing Value)

Kita bisa gunakan function .isna().sum() ke df, untuk mendapatkan jumlah (sum) berapa banyak missing value (yang is NA).

In [ ]:
df.isna().sum()



entity_id                         0
pendapatan                    17966
pengeluaran                       0
jml_anggota_keluarga              0
biaya_rent_tempat_tinggal         0
total_pendapatan_tahunan      17966
tingkat_pendidikan            19948
jumlah_pekerja_di_keluarga        0
kota                              0
dtype: int64

### FillNA

Untuk kolom "tingkat_pendidikan", kita periksa dulu apa isi data yang ada di sana.

In [ ]:
df['tingkat_pendidikan'].value_counts()

tingkat_pendidikan
Master (S2)      127281
Sarjana (S1)      67084
Diploma (D3)      66999
Doktor (S3)       40314
Tidak Sekolah     33374
Name: count, dtype: int64

Misalkan kita isi data kosong dengan "Tidak Diketahui". Jadi, digunakan .fillna("Tidak Diketahui").

Karena kita ingin mengisi value ini spesifik untuk kolom "tingkat_pendidikan", maka function dikenakan hanya di kolom tadi.

In [ ]:
df['tingkat_pendidikan'] = df['tingkat_pendidikan'].fillna("Tidak Diketahui")

0            Diploma (D3)
1             Master (S2)
2             Doktor (S3)
3             Doktor (S3)
4             Master (S2)
               ...       
354995       Sarjana (S1)
354996        Master (S2)
354997    Tidak Diketahui
354998        Doktor (S3)
354999       Diploma (D3)
Name: tingkat_pendidikan, Length: 355000, dtype: object


### DropNA

Untuk kolom "pendapatan" dan "total_pendapatan_tahunan", misalnya data kosong akan dihilangkan.

In [ ]:
df = df.dropna()

Cek missing value sekali lagi untuk memastikan semua data kosong sudah dihandle

In [ ]:
df.isna().sum()

entity_id                     0
pendapatan                    0
pengeluaran                   0
jml_anggota_keluarga          0
biaya_rent_tempat_tinggal     0
total_pendapatan_tahunan      0
tingkat_pendidikan            0
jumlah_pekerja_di_keluarga    0
kota                          0
dtype: int64

## Cek Data Duplikat

Kita bisa gunakan function .duplicated() ke df, untuk mendapatkan mana saja data yang terduplikat.

In [ ]:
df[df.duplicated()]

entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
350000      66402     51000.0      15000.0                   4.0   
350001      72320     32000.0      20500.0                   3.0   
350002     191770     23500.0       2000.0                   2.0   
350003      72777     63000.0       8500.0                   6.0   
350004     291463     28000.0      45000.0                   6.0   
...           ...         ...          ...                   ...   
354995     139379     25500.0      16000.0                   2.0   
354996     265535     78000.0      19500.0                   5.0   
354997     312041     28000.0      22000.0                   6.0   
354998     311871     14000.0      47000.0                   7.0   
354999     282193     48500.0       8000.0                   6.0   

        biaya_rent_tempat_tinggal  total_pendapatan_tahunan  \
350000                          0                  610000.0   
350001                      38440                  388500.0   
350002                       3054                  318000.0   
350003                      19152                  697000.0   
350004                          0                  364500.0   
...                           ...                       ...   
354995                       2850                  300500.0   
354996                      10145                  894000.0   
354997                          0                  355000.0   
354998                          0                  158000.0   
354999                          0                  690500.0   

       tingkat_pendidikan  jumlah_pekerja_di_keluarga               kota  
350000    Tidak Diketahui                         3.0    Jakarta Selatan  
350001    Tidak Diketahui                         2.0        Bekasi Kota  
350002    Tidak Diketahui                         1.0  Tangerang Selatan  
350003        Doktor (S3)                         2.0     Tangerang Kota  
350004    Tidak Diketahui                         1.0    Jakarta Selatan  
...                   ...                         ...                ...  
354995       Sarjana (S1)                         1.0  Tangerang Selatan  
354996        Master (S2)                         3.0    Jakarta Selatan  
354997    Tidak Diketahui                         1.0          Tangerang  
354998        Doktor (S3)                         2.0              Bogor  
354999       Diploma (D3)                         2.0          Tangerang  

[4734 rows x 9 columns]

Menghilangkan data yang duplikat, dengan menerapkan function .drop_duplicates() ke variabel df.

In [ ]:
df = df.drop_duplicates()

Periksa lagi untuk memastikan data yang terduplikat sudah dihapus

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [entity_id, pendapatan, pengeluaran, jml_anggota_keluarga, biaya_rent_tempat_tinggal, total_pendapatan_tahunan, tingkat_pendidikan, jumlah_pekerja_di_keluarga, kota]
Index: []

## Konversi Tipe Data

Dilakukan cek dulu untuk tipe data masing-masing kolom dengan .dtypes:

In [ ]:
df.dtypes

entity_id                       int64
pendapatan                    float64
pengeluaran                   float64
jml_anggota_keluarga          float64
biaya_rent_tempat_tinggal       int64
total_pendapatan_tahunan      float64
tingkat_pendidikan             object
jumlah_pekerja_di_keluarga    float64
kota                           object
dtype: object

Didapat:

- entity_id bertipe data "int", akan diubah jadi "string"
- jml_anggota_keluarga dan jumlah_pekerja_di_keluarga bertipe "float", akan diubah jadi "int"
- biaya_rent_tempat_tinggal karena berupa monetary, akan diubah dari "int" jadi "float"

Untuk mengkonversi tipe data, digunakan function .astype().

In [ ]:
# Mengubah menjadi string dengan .astype(str)
df['entity_id'] = df['entity_id'].astype(str)

# Mengubah menjadi "int" dengan .astype(int)
df['jml_anggota_keluarga'] = df['jml_anggota_keluarga'].astype(int)
df['jumlah_pekerja_di_keluarga'] = df['jumlah_pekerja_di_keluarga'].astype(int)

# Mengubah menjadi "float" dengan .astype(float)
df['biaya_rent_tempat_tinggal'] = df['biaya_rent_tempat_tinggal'].astype(float)

Periksa lagi untuk memastikan apakah tipe data sudah terubah

In [ ]:
df.dtypes

entity_id                      object
pendapatan                    float64
pengeluaran                   float64
jml_anggota_keluarga            int64
biaya_rent_tempat_tinggal     float64
total_pendapatan_tahunan      float64
tingkat_pendidikan             object
jumlah_pekerja_di_keluarga      int64
kota                           object
dtype: object

### Data Summarizing

Menghitung banyaknya data pendapatan yang dipunyai, dengan menerapkan .count() ke kolom "pendapatan": df['pendapatan']

In [ ]:
df['pendapatan'].count()

np.int64(337034)

Mengambil total (jumlah) pendapatan: .sum()

In [ ]:
df['pendapatan'].sum()

np.float64(13990658500.0)


Mengambil nilai minimum (.min()) dan maximum (.max()):

In [ ]:
df['pendapatan'].min()

np.float64(3000.0)

In [ ]:
df['pendapatan'].max()

np.float64(135000.0)

Mengambil nilai rata-rata (.mean()):

In [ ]:
df['pendapatan'].mean()

np.float64(41511.11905623765)

Mengambil nilai sebaran / standar deviasi (.std()):

In [ ]:
df['pendapatan'].std()

np.float64(26256.009322411464)

Mengambil beberapa metrics descriptive statistics sekaligus dengan menerapkan .describe() ke df['pendapatan']

In [ ]:
df['pendapatan'].describe()

count    337034.000000
mean      41511.119056
std       26256.009322
min        3000.000000
25%       22500.000000
50%       36000.000000
75%       52500.000000
max      135000.000000
Name: pendapatan, dtype: float64

Jika diterapkan ke keseluruhan data di df, maka function .describe() akan diterapkan ke seluruh kolom.

In [ ]:
df.describe()

entity_id     pendapatan    pengeluaran  jml_anggota_keluarga  \
count  355000.000000  337034.000000  355000.000000         355000.000000   
mean   175017.826318   41511.119056   18817.664789              4.053499   
std    101041.185830   26256.009322   12160.459939              1.463103   
min         1.000000    3000.000000    1500.000000              1.000000   
25%     87491.750000   22500.000000    9500.000000              3.000000   
50%    175029.500000   36000.000000   16000.000000              4.000000   
75%    262538.250000   52500.000000   24000.000000              5.000000   
max    350000.000000  135000.000000   70500.000000              7.000000   

       biaya_rent_tempat_tinggal  total_pendapatan_tahunan  \
count              355000.000000              3.370340e+05   
mean                 3050.823583              5.006859e+05   
std                  6184.042507              3.234734e+05   
min                     0.000000              3.050000e+04   
25%                     0.000000              2.645000e+05   
50%                     0.000000              4.280000e+05   
75%                  3493.000000              6.430000e+05   
max                 47507.000000              1.925500e+06   

       jumlah_pekerja_di_keluarga  
count               355000.000000  
mean                     1.439096  
std                      0.717004  
min                      1.000000  
25%                      1.000000  
50%                      1.000000  
75%                      2.000000  
max                      4.000000

## Persiapan untuk analisis data

### Filtering Data

Misalnya, akan difilter data yang hanya berasal dari Jakarta Selatan.

In [ ]:
# Kondisi: kolom "kota" harus SAMA DENGAN (==) Jakarta Selatan
condition = (df['kota'] == 'Jakarta Selatan')

# Filter datanya dengan memasukkan condition ke df[]
df[condition]

entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
15             16     25000.0      49000.0                   4.0   
47             48     48000.0       7500.0                   3.0   
70             71     73000.0      11000.0                   4.0   
86             87     75500.0      13500.0                   4.0   
106           107     12000.0      14000.0                   6.0   
...           ...         ...          ...                   ...   
354983      66090     28500.0      24000.0                   5.0   
354988       2232     11500.0      12500.0                   4.0   
354993     134172     70000.0      50500.0                   6.0   
354994     121417     22500.0       2000.0                   4.0   
354996     265535     78000.0      19500.0                   5.0   

        biaya_rent_tempat_tinggal  total_pendapatan_tahunan  \
15                              0                  349000.0   
47                           4877                  631500.0   
70                              0                  884500.0   
86                              0                 1021500.0   
106                          3411                  152500.0   
...                           ...                       ...   
354983                          0                  307500.0   
354988                          0                  117000.0   
354993                          0                  760500.0   
354994                       1112                  274500.0   
354996                      10145                  894000.0   

       tingkat_pendidikan  jumlah_pekerja_di_keluarga             kota  
15           Diploma (D3)                         1.0  Jakarta Selatan  
47            Master (S2)                         1.0  Jakarta Selatan  
70            Master (S2)                         1.0  Jakarta Selatan  
86           Sarjana (S1)                         1.0  Jakarta Selatan  
106          Sarjana (S1)                         1.0  Jakarta Selatan  
...                   ...                         ...              ...  
354983       Sarjana (S1)                         1.0  Jakarta Selatan  
354988                NaN                         1.0  Jakarta Selatan  
354993        Master (S2)                         1.0  Jakarta Selatan  
354994        Doktor (S3)                         2.0  Jakarta Selatan  
354996        Master (S2)                         3.0  Jakarta Selatan  

[27290 rows x 9 columns]

Misalnya, akan difilter data yang hanya berasal dari Jakarta Selatan DAN jumlah anggota keluarganya lebih dari 5.

In [ ]:
# Kondisi 1: kota SAMA DENGAN Jakarta Selatan
condition1 = (df['kota'] == 'Jakarta Selatan')
# Kondisi 2: jumlah anggota keluarga LEBIH DARI (>) 5
condition2 = (df['jml_anggota_keluarga'] > 5)

# Filter datanya dengan memasukkan condition ke df[]. Tiap condition diberi kurung ()
df[(condition1) & (condition2)]

entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
106           107     12000.0      14000.0                   6.0   
154           155     28000.0       9500.0                   7.0   
221           222         NaN      11500.0                   6.0   
247           248     18500.0      10000.0                   6.0   
274           275     62000.0      11000.0                   7.0   
...           ...         ...          ...                   ...   
354923     240523     20000.0      54500.0                   6.0   
354950     152098     49500.0      24000.0                   6.0   
354953     237456     16500.0      25000.0                   6.0   
354975       5449     10000.0      14500.0                   6.0   
354993     134172     70000.0      50500.0                   6.0   

        biaya_rent_tempat_tinggal  total_pendapatan_tahunan  \
106                          3411                  152500.0   
154                          4569                  378500.0   
221                             0                       NaN   
247                             0                  223000.0   
274                          4666                  723500.0   
...                           ...                       ...   
354923                       7296                  265000.0   
354950                       4753                  572500.0   
354953                          0                  224500.0   
354975                          0                  143500.0   
354993                          0                  760500.0   

       tingkat_pendidikan  jumlah_pekerja_di_keluarga             kota  
106          Sarjana (S1)                         1.0  Jakarta Selatan  
154           Master (S2)                         1.0  Jakarta Selatan  
221           Master (S2)                         3.0  Jakarta Selatan  
247           Master (S2)                         1.0  Jakarta Selatan  
274          Sarjana (S1)                         1.0  Jakarta Selatan  
...                   ...                         ...              ...  
354923        Master (S2)                         2.0  Jakarta Selatan  
354950        Master (S2)                         1.0  Jakarta Selatan  
354953       Diploma (D3)                         1.0  Jakarta Selatan  
354975                NaN                         2.0  Jakarta Selatan  
354993        Master (S2)                         1.0  Jakarta Selatan  

[6194 rows x 9 columns]

## Membuat Kolom Baru

Misalnya, akan dibuat kolom baru untuk menghitung "saving" dan "pendapatan per kapita" dari masing-masing row:

- saving = pendapatan - pengeluaran
- pendapatan per kapita = total_pendapatan_tahunan / jml_anggota_keluarga

Cara menambah kolom baru: df['nama_kolom_baru'] = operasi yang dilakukan.

In [ ]:
df['saving'] = df['pendapatan'] - df['pengeluaran']
df['pendapatan_per_kapita'] = df['total_pendapatan_tahunan'] / df['jml_anggota_keluarga']

kita bisa cek apakah kolom tertambah atau tidak

In [ ]:
df.head()

entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
0          1     55000.0       9500.0                   2.0   
1          2     99500.0      12000.0                   4.0   
2          3     94500.0      15000.0                   6.0   
3          4     86500.0      12000.0                   1.0   
4          5     70500.0       8000.0                   4.0   

   biaya_rent_tempat_tinggal  total_pendapatan_tahunan tingkat_pendidikan  \
0                       2375                  580500.0       Diploma (D3)   
1                       7153                 1116000.0        Master (S2)   
2                      11752                 1024000.0        Doktor (S3)   
3                          0                 1058500.0        Doktor (S3)   
4                          0                 1003000.0        Master (S2)   

   jumlah_pekerja_di_keluarga         kota   saving  pendapatan_per_kapita  
0                         1.0  Bekasi Kota  45500.0           2.902500e+05  
1                         1.0    Tangerang  87500.0           2.790000e+05  
2                         1.0    Tangerang  79500.0           1.706667e+05  
3                         1.0  Bekasi Kota  74500.0           1.058500e+06  
4                         4.0    Tangerang  62500.0           2.507500e+05

## Menggabungkan Dataset

Misalnya data baru yang ingin digabungkan, bisa diperoleh dan sudah diload dalam variabel df2 dengan syntax berikut:

In [ ]:
url2 = 'https://raw.githubusercontent.com/orkvacy/dummy-data/refs/heads/main/area.csv'
df2 = pd.read_csv(url2)
df2.head()

kota         area
0    Jakarta Timur  DKI Jakarta
1    Jakarta Pusat  DKI Jakarta
2  Jakarta Selatan  DKI Jakarta
3    Jakarta Barat  DKI Jakarta
4     Jakarta Urat  DKI Jakarta

Kita bisa lihat bahwa di data df2 terdapat kolom yang sama seperti data utama df kita, yaitu kolom "kota".

Misalkan dilakukan inner join untuk mendapatkan nama area di dataframe utama kita di df, lalu simpan hasilnya sebagai df_final:

In [ ]:
df_final = df.merge(df2, on='kota', how='inner')
df_final

entity_id  pendapatan  pengeluaran  jml_anggota_keluarga  \
0               1     55000.0       9500.0                   2.0   
1               2     99500.0      12000.0                   4.0   
2               3     94500.0      15000.0                   6.0   
3               4     86500.0      12000.0                   1.0   
4               5     70500.0       8000.0                   4.0   
...           ...         ...          ...                   ...   
327645     139379     25500.0      16000.0                   2.0   
327646     265535     78000.0      19500.0                   5.0   
327647     312041     28000.0      22000.0                   6.0   
327648     311871     14000.0      47000.0                   7.0   
327649     282193     48500.0       8000.0                   6.0   

        biaya_rent_tempat_tinggal  total_pendapatan_tahunan  \
0                            2375                  580500.0   
1                            7153                 1116000.0   
2                           11752                 1024000.0   
3                               0                 1058500.0   
4                               0                 1003000.0   
...                           ...                       ...   
327645                       2850                  300500.0   
327646                      10145                  894000.0   
327647                          0                  355000.0   
327648                          0                  158000.0   
327649                          0                  690500.0   

       tingkat_pendidikan  jumlah_pekerja_di_keluarga               kota  \
0            Diploma (D3)                         1.0        Bekasi Kota   
1             Master (S2)                         1.0          Tangerang   
2             Doktor (S3)                         1.0          Tangerang   
3             Doktor (S3)                         1.0        Bekasi Kota   
4             Master (S2)                         4.0          Tangerang   
...                   ...                         ...                ...   
327645       Sarjana (S1)                         1.0  Tangerang Selatan   
327646        Master (S2)                         3.0    Jakarta Selatan   
327647                NaN                         1.0          Tangerang   
327648        Doktor (S3)                         2.0              Bogor   
327649       Diploma (D3)                         2.0          Tangerang   

         saving  pendapatan_per_kapita         area  
0       45500.0           2.902500e+05       Bekasi  
1       87500.0           2.790000e+05    Tangerang  
2       79500.0           1.706667e+05    Tangerang  
3       74500.0           1.058500e+06       Bekasi  
4       62500.0           2.507500e+05    Tangerang  
...         ...                    ...          ...  
327645   9500.0           1.502500e+05    Tangerang  
327646  58500.0           1.788000e+05  DKI Jakarta  
327647   6000.0           5.916667e+04    Tangerang  
327648 -33000.0           2.257143e+04        Bogor  
327649  40500.0           1.150833e+05    Tangerang  

[327650 rows x 12 columns]